"""Evolution Manager - Phase 7: Persistent Intelligence Layer.

AI generates proposals with historical context.
Never modifies running runtime directly.
"""
import os
import sys
import json
import time
import shutil
from datetime import datetime

_current_dir = os.path.dirname(__file__)
_project_root = os.path.dirname(_current_dir)
sys.path.insert(0, _project_root)

from aegisos.db.sqlite_store import create_evolution_job, update_evolution_job_status
from aegisos.ai.executor import execute_with_budget_guard
from aegisos.memory.retrieval import get_evolution_context, format_retrieval_context
from aegisos.memory.vector_index import get_vector_index, compute_embedding_id

# Paths
EVOLUTION_DIR = os.path.join(_project_root, "evolution")
PROPOSALS_DIR = os.path.join(EVOLUTION_DIR, "proposals")
STAGING_DIR = os.path.join(EVOLUTION_DIR, "staging")
RUNTIME_DIR = os.path.join(_project_root, "runtime")


def ensure_directories():
    """Ensure evolution directories exist."""
    os.makedirs(PROPOSALS_DIR, exist_ok=True)
    os.makedirs(STAGING_DIR, exist_ok=True)


def generate_proposal_id() -> str:
    """Generate unique proposal ID."""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    return f"evo_{timestamp}"


def create_proposal_manifest(proposal_path: str, goal: str, files_changed: list, 
                             risk_level: str = "medium", justification: str = "",
                             historical_context: dict = None):
    """Create manifest.json for proposal.
    
    Phase 7: AI MUST output justification_against_history.
    If missing, proposal is rejected.
    
    Args:
        proposal_path: Path to proposal directory
        goal: Evolution goal description
        files_changed: List of files to be modified
        risk_level: low/medium/high/critical
        justification: Why this won't repeat past failures
        historical_context: Retrieved historical cases
    """
    manifest = {
        "proposal_id": os.path.basename(proposal_path),
        "goal": goal,
        "target_version": "v1.1",
        "files_changed": files_changed,
        "risk_level": risk_level,
        "requires_migration": False,
        "created_at": time.time(),
        "author": "AI",
        # Phase 7: Required new fields
        "justification_against_history": justification,
        "historical_failures_count": len(historical_context.get("historical_failures", [])) if historical_context else 0,
        "historical_successes_count": len(historical_context.get("historical_successes", [])) if historical_context else 0
    }
    
    manifest_path = os.path.join(proposal_path, "manifest.json")
    with open(manifest_path, "w") as f:
        json.dump(manifest, f, indent=2)
    
    return manifest


def mock_ai_generate_patch_with_context(task_id: int, goal: str, 
                                        historical_context: str,
                                        risk_forecast: dict) -> dict:
    """Mock AI call to generate patch bundle with historical awareness.
    
    Phase 7: AI receives historical successes/failures
    and MUST explain why this attempt won't repeat past failures.
    
    Returns:
        Dictionary with patch content, test files, and justification
    """
    # In production, this would call actual AI with historical context
    # through execute_with_budget_guard()
    
    # Parse risk level from forecast
    risk_level = risk_forecast.get("risk_level", "medium")
    
    # Generate justification based on historical context
    failures = risk_forecast.get("similar_cases_count", 0) > 0 and risk_forecast.get("failure_rate", 0) > 0
    
    if failures:
        justification = (
            f"Historical analysis shows {risk_forecast.get('failure_rate', 0)*100:.0f}% failure rate "
            f"for similar changes. This proposal addresses previous issues by: "
            f"(1) Adding comprehensive tests, "
            f"(2) Implementing gradual rollout, "
            f"(3) Including rollback mechanism. "
            f"Risk level: {risk_level}."
        )
    else:
        justification = (
            "No similar historical failures found. "
            "This follows established patterns with added safeguards. "
            "Proceeding with standard validation."
        )
    
    patch_content = f"""# Evolution Patch for: {goal}
# Generated by AI (Phase 7 with historical awareness)

## Summary
This proposal was generated after analyzing {risk_forecast.get('similar_cases_count', 0)} similar past cases.
Risk assessment: {risk_level}

## Historical Context Considered
{historical_context[:500]}...

## Justification
{justification}

## Files Changed
- executor/task_runner.py: Add better error handling with lessons from history

## Diff (simulated)
--- a/executor/task_runner.py
+++ b/executor/task_runner.py
@@ -10,6 +10,9 @@ def run_once():
     try:
         # Existing logic
+        # Phase 7: Learning from past failures
+        # Added validation before execution
+        print(f"[Evolution] Task {{task_id}} validated and starting")
         pass
     except Exception as e:
         # Improved error handling based on historical data
"""
    
    test_content = f"""# Tests for Evolution Proposal
# Goal: {goal}
# Risk Level: {risk_level}

def test_evolution_improvement():
    \"\"\"Test that evolution changes work correctly.\"\"\"
    # Validated against historical failures
    assert True, "Evolution test with historical awareness"

def test_rollback_safety():
    \"\"\"Ensure safe rollback is possible.\"\"\"
    assert True, "Rollback safety check"
"""
    
    return {
        "patch": patch_content,
        "tests": test_content,
        "files_changed": ["executor/task_runner.py"],
        "risk_level": risk_level,
        "justification": justification
    }


def create_evolution_proposal(task_id: int, goal: str) -> str:
    """Create evolution proposal from request.
    
    Phase 7 Workflow:
    1. Retrieve historical similar cases
    2. Compute risk forecast
    3. Provide context to AI
    4. AI generates patch with justification
    5. Validate justification exists
    6. Register in database
    
    Args:
        task_id: Task ID that triggered evolution
        goal: Evolution goal description
    
    Returns:
        Proposal path
    """
    ensure_directories()
    
    # Phase 7: Step 1 & 2 - Retrieve historical context and risk forecast
    print(f"[Evolution] Retrieving historical context for: {goal}")
    historical_context, risk_forecast = get_evolution_context(goal)
    
    print(f"[Evolution] Risk assessment: {risk_forecast['risk_level']}")
    print(f"[Evolution] Found {risk_forecast['similar_cases_count']} similar cases")
    print(f"[Evolution] Failure rate: {risk_forecast['failure_rate']*100:.0f}%")
    
    # Phase 7: Critical - If risk is critical, require manual review
    if risk_forecast["risk_level"] == "critical":
        print(f"[Evolution] WARNING: Critical risk detected!")
        print(f"[Evolution] Recommendation: {risk_forecast['recommendation']}")
    
    # Generate unique proposal ID
    proposal_id = generate_proposal_id()
    proposal_path = os.path.join(PROPOSALS_DIR, proposal_id)
    
    # Create proposal directory
    os.makedirs(proposal_path, exist_ok=True)
    
    # Phase 7: Step 3 & 4 - Call AI with historical context
    # In mock mode, we use local generation
    # In production: execute_with_budget_guard(task_id, "kimi", prompt_with_context, ai_call_func)
    patch_bundle = mock_ai_generate_patch_with_context(
        task_id, 
        goal, 
        historical_context,
        risk_forecast
    )
    
    # Phase 7: Step 5 - Validate justification exists
    justification = patch_bundle.get("justification", "")
    if not justification or len(justification) < 20:
        # Reject proposal - missing required justification
        error_msg = "Proposal rejected: Missing justification_against_history"
        print(f"[Evolution] {error_msg}")
        
        # Write error file
        with open(os.path.join(proposal_path, "REJECTED.txt"), "w") as f:
            f.write(error_msg)
        
        # Still create minimal manifest for record
        manifest = create_proposal_manifest(
            proposal_path=proposal_path,
            goal=goal,
            files_changed=[],
            risk_level="rejected",
            justification="REJECTED: " + error_msg,
            historical_context=None
        )
        
        # Register as rejected
        job_id = create_evolution_job(task_id, proposal_path)
        update_evolution_job_status(job_id, "rejected")
        
        return proposal_path
    
    # Write patch file
    patch_path = os.path.join(proposal_path, "patch.diff")
    with open(patch_path, "w") as f:
        f.write(patch_bundle["patch"])
    
    # Write test file
    test_path = os.path.join(proposal_path, "new_tests.py")
    with open(test_path, "w") as f:
        f.write(patch_bundle["tests"])
    
    # Write historical context for review
    context_path = os.path.join(proposal_path, "historical_context.txt")
    with open(context_path, "w") as f:
        f.write(historical_context)
    
    # Create manifest with justification
    manifest = create_proposal_manifest(
        proposal_path=proposal_path,
        goal=goal,
        files_changed=patch_bundle["files_changed"],
        risk_level=patch_bundle["risk_level"],
        justification=justification,
        historical_context={
            "successes": patch_bundle.get("historical_successes_count", 0),
            "failures": patch_bundle.get("historical_failures_count", 0)
        }
    )
    
    # Register in database
    job_id = create_evolution_job(task_id, proposal_path)
    
    # Add to vector index for future retrieval
    context_text = f"{goal} {justification}"
    embedding_id = compute_embedding_id(context_text)
    index = get_vector_index()
    index.add_memory(job_id, goal, justification)
    
    print(f"[Evolution] Created proposal: {proposal_id}")
    print(f"[Evolution] Job ID: {job_id}")
    print(f"[Evolution] Path: {proposal_path}")
    print(f"[Evolution] Justification: {justification[:100]}...")
    
    return proposal_path


def get_proposal_manifest(proposal_path: str) -> dict:
    """Read proposal manifest."""
    manifest_path = os.path.join(proposal_path, "manifest.json")
    if os.path.exists(manifest_path):
        with open(manifest_path, "r") as f:
            return json.load(f)
    return {}


def list_proposals():
    """List all proposals."""
    ensure_directories()
    proposals = []
    for item in os.listdir(PROPOSALS_DIR):
        item_path = os.path.join(PROPOSALS_DIR, item)
        if os.path.isdir(item_path):
            manifest = get_proposal_manifest(item_path)
            proposals.append({
                "id": item,
                "path": item_path,
                "manifest": manifest
            })
    return proposals
